/*
This program does most of the heavy lifting. It will be used to enter confidential data.
 */
package Logins;

/**
 *
 * @author Vinayak Saxena
 */
public class PatientGUI extends javax.swing.JFrame {
    //Original 2d array introduced
    String[][] patientinfo = new String[20000][9];
    //Counter introduced, being used to see which row to add data
    int patient_counter = 0;
    
    /**
     * Creates new form PatientGUI
     */
    public PatientGUI() {
        initComponents();
    }
    public PatientGUI(String a[][]){
        //Passed global array to constructor
        initComponents();
        patientinfo=a;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Priority_Group = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        First_Name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Last_Name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Information = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        priority1 = new javax.swing.JRadioButton();
        priority2 = new javax.swing.JRadioButton();
        priority3 = new javax.swing.JRadioButton();
        priority4 = new javax.swing.JRadioButton();
        priority5 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Description = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BP = new javax.swing.JTextField();
        BT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        HR = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        BR = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        view_info = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Enter Information");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Welcome to the Kitchener Hospital");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("First Name:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Last Name:");

        Information.setForeground(new java.awt.Color(0, 255, 0));
        Information.setText("Enter Information");
        Information.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformationActionPerformed(evt);
            }
        });

        Back.setForeground(new java.awt.Color(255, 0, 0));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Priority (Triage)");

        Priority_Group.add(priority1);
        priority1.setForeground(new java.awt.Color(0, 0, 255));
        priority1.setText("1 (MINOR)");

        Priority_Group.add(priority2);
        priority2.setForeground(new java.awt.Color(0, 0, 255));
        priority2.setText("2 (MODERATE)");

        Priority_Group.add(priority3);
        priority3.setForeground(new java.awt.Color(0, 0, 255));
        priority3.setText("3 (MAJOR)");

        Priority_Group.add(priority4);
        priority4.setForeground(new java.awt.Color(0, 0, 255));
        priority4.setText("4 (URGENT)");

        Priority_Group.add(priority5);
        priority5.setForeground(new java.awt.Color(0, 0, 255));
        priority5.setText("5 (EMERGENCY)");

        Description.setColumns(20);
        Description.setRows(5);
        jScrollPane1.setViewportView(Description);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Description");

        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Blood Pressure:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Vitals");

        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Body Temperature: ");

        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Pulse: ");

        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Breathing Rate: ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Name");

        view_info.setForeground(new java.awt.Color(0, 255, 0));
        view_info.setText("View Patient Information");
        view_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_infoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(17, 17, 17)
                                .addComponent(Last_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(17, 17, 17)
                                .addComponent(First_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel8))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18)
                                    .addComponent(BR, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BP, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(HR, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(BT, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priority1)
                            .addComponent(priority2)
                            .addComponent(priority3)
                            .addComponent(priority4)
                            .addComponent(priority5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel12)
                                .addGap(144, 144, 144)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Information)
                                .addGap(10, 10, 10)
                                .addComponent(view_info)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(115, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(65, 65, 65)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(priority1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(priority2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(First_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Last_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priority3)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(priority4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(priority5))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(BP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(BT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(HR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(BR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Information)
                    .addComponent(Back)
                    .addComponent(view_info))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel4)
                    .addContainerGap(346, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformationActionPerformed
        // TODO add your handling code here:
        
        /*This set of code is used to check for which row patient data is on
        Since the patientinfo 2d array is being passed to different screens,
        I chose to add a patient counter that goes up everytime the user enters data
        I then simply added that counter to the 2d array that holds all patient information
        So, whenever I want to use the counter, I can simply call it from the array
        Initially, it will be null, so it's set to 0
        */
         
       
        if(patientinfo[0][8]==null){
            patient_counter=0;
        }
        //If it's not null, that means a counter value has been assigned. So it will pull
        //that value, and use that as the counter
        else{
            patient_counter=Integer.parseInt(patientinfo[0][8]);
        }
        
        
        
        //Getting important information from textfields
        //BP = Blood Pressure, BT = Body Temp., HR = Pulse, BR = Breathing rate
        String firstname, lastname, desc, bp,bt,hr,br;
        firstname=(First_Name.getText()).toString();
        lastname=(Last_Name.getText()).toString();
        desc=(Description.getText()).toString();
        bp=(BP.getText()).toString();
        bt=(BT.getText()).toString();
        hr=(HR.getText()).toString();
        br=(BR.getText()).toString();
        //Assigning name
        patientinfo[patient_counter][0]=firstname;
        patientinfo[patient_counter][1]=lastname;
        
        
        
        //Assignined triage priority from radio buttons
        if (priority1.isSelected()){
            patientinfo[patient_counter][2]="1";
        } else if(priority2.isSelected()){
            patientinfo[patient_counter][2]="2"; 
        } else if(priority3.isSelected()){
            patientinfo[patient_counter][2]="3";
        } else if(priority4.isSelected()){
            patientinfo[patient_counter][2]="4";
        } else if(priority5.isSelected()){
            patientinfo[patient_counter][2]="5";
        }
        
        
        
        //Assigning vital signs
        patientinfo[patient_counter][3]=bp;
        patientinfo[patient_counter][4]=bt;
        patientinfo[patient_counter][5]=hr;
        patientinfo[patient_counter][6]=br;
        patientinfo[patient_counter][7]=desc;
        
        //After all data has been entered, increase the counter by one
        patient_counter+=1;
        
        //Sets the new counter value to the array
        patientinfo[0][8]=Integer.toString(patient_counter);
        //Clears text fields
        First_Name.setText("");
        Last_Name.setText("");
        Description.setText("");
        BP.setText("");
        BT.setText("");
        HR.setText("");
        BR.setText("");
        
        //Clears radio buttons
        priority1.setSelected(false);
        priority2.setSelected(false);
        priority3.setSelected(false);
        priority4.setSelected(false);
        priority5.setSelected(false);
        
    }//GEN-LAST:event_InformationActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        //If you want to go back, close this screen, and open new screen passing 2d array
        setVisible(false);
        new LoginS(patientinfo).setVisible(true);


    }//GEN-LAST:event_BackActionPerformed

    private void view_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_infoActionPerformed
        // TODO add your handling code here:
        
        //Same thing as above, close this screen and open new ListInfo file whilst passing 2d array
        setVisible(false);
        new ListInfo(patientinfo).setVisible(true);
 
    }//GEN-LAST:event_view_infoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BP;
    private javax.swing.JTextField BR;
    private javax.swing.JTextField BT;
    private javax.swing.JButton Back;
    private javax.swing.JTextArea Description;
    private javax.swing.JTextField First_Name;
    private javax.swing.JTextField HR;
    private javax.swing.JButton Information;
    private javax.swing.JTextField Last_Name;
    private javax.swing.ButtonGroup Priority_Group;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton priority1;
    private javax.swing.JRadioButton priority2;
    private javax.swing.JRadioButton priority3;
    private javax.swing.JRadioButton priority4;
    private javax.swing.JRadioButton priority5;
    private javax.swing.JButton view_info;
    // End of variables declaration//GEN-END:variables
}
